#!/usr/bin/env zsh

__symfony_complete_commands() {
    command sed -nE \
        -e '1,/Available commands/d' \
        -e 's/([[]|[]])/\\\1/g' \
        -e 's/:/\\\:/g' \
        -e 's/^  ([[:alnum:]\\:-]+).*  (.*)$/\1[\2]/p'
}

__symfony_complete_commands "$@"
