#!/usr/bin/env zsh

_symfony_complete_options() {
    command sed -nr \
        -e '1,/^Options/d' \
        -e '/^Help/,$d' \
        -e 's/([[]|[]])/\\\1/g' \
        -e 's/:/\\\:/g' \
        -e 's/^.*[[:space:]](--[[:alnum:]-]+=?).*  (.*)$/\1[\2]/p'
}

_symfony_complete_options "$@"
